#1.Binary Classification

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#Import Library

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import *

#Load Dataset

In [ ]:
df = pd.read_csv('/content/Social_Network_Ads.csv')

In [ ]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


#Data Split

In [ ]:
#X adalah variabel indepenen - berisi AGE dan Estimated Salary
X = df.iloc[:, [2, 3]].values

#y adalah dependen - berisi fitur Purchased
y = df.iloc[:, -1].values

In [ ]:
print('X : \n',X[:5])
print('\ny : \n',y[:5])

X : 
 [[   19 19000]
 [   35 20000]
 [   26 43000]
 [   27 57000]
 [   19 76000]]

y : 
 [0 0 0 0 0]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size = 0.20,
                                                    random_state = 0)

In [ ]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(320, 2)
(320,)
(80, 2)
(80,)


#Create clasifier model

In [ ]:
classifier_model_binary = GaussianNB()
classifier_model_binary.fit(X_train, y_train)

GaussianNB()

#Predict test data

In [ ]:
y_pred = classifier_model_binary.predict(X_test)

In [ ]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [ ]:
# Menggunakan model Gaussian Naive Bayes
classifier_model_binary = GaussianNB()

# Melatih model
classifier_model_binary.fit(X_train, y_train)

# Melakukan prediksi probabilitas
probabilities = classifier_model_binary.predict_proba(X_test)

# Menampilkan hasil prediksi probabilitas
print(probabilities)

[[0.89147043 0.10852957]
 [0.84097849 0.15902151]
 [0.85177346 0.14822654]
 [0.91910807 0.08089193]
 [0.89836193 0.10163807]
 [0.95434022 0.04565978]
 [0.90414431 0.09585569]
 [0.03556946 0.96443054]
 [0.98918806 0.01081194]
 [0.50281633 0.49718367]
 [0.95249262 0.04750738]
 [0.96371556 0.03628444]
 [0.85930139 0.14069861]
 [0.7299999  0.2700001 ]
 [0.97431305 0.02568695]
 [0.47994231 0.52005769]
 [0.79297558 0.20702442]
 [0.97847631 0.02152369]
 [0.00422727 0.99577273]
 [0.86019336 0.13980664]
 [0.89871448 0.10128552]
 [0.00500754 0.99499246]
 [0.75594755 0.24405245]
 [0.13376637 0.86623363]
 [0.97909645 0.02090355]
 [0.0047035  0.9952965 ]
 [0.9182418  0.0817582 ]
 [0.92764915 0.07235085]
 [0.84823267 0.15176733]
 [0.86172083 0.13827917]
 [0.9678875  0.0321125 ]
 [0.78129467 0.21870533]
 [0.11042736 0.88957264]
 [0.86111685 0.13888315]
 [0.97916887 0.02083113]
 [0.99139079 0.00860921]
 [0.97234947 0.02765053]
 [0.91209682 0.08790318]
 [0.93926899 0.06073101]
 [0.39193642 0.60806358]


#Evaluate

In [ ]:
print(classification_report(y_test,y_pred,zero_division=0))

              precision    recall  f1-score   support

           0       0.93      0.97      0.95        58
           1       0.90      0.82      0.86        22

    accuracy                           0.93        80
   macro avg       0.92      0.89      0.90        80
weighted avg       0.92      0.93      0.92        80



#Predict New Data

In [ ]:
def predict_one(age, salary):
  print('Prediction : ', classifier_model_binary.predict([[age, salary]]))
  print('Probability : ', classifier_model_binary.predict_proba([[age, salary]]))

In [ ]:
predict_one(39,100000)

Prediction :  [1]
Probability :  [[0.47948201 0.52051799]]


#2.Multiclass Classification

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import *

In [ ]:
df_train = pd.read_excel("/content/data_train.xlsx")
df_test = pd.read_csv("/content/data_test.csv")

In [ ]:
df_train.head(100)

Jurusan  Matematika  Bahasa Inggris  Bahasa Indonesia  \
0         Matematika          92              86                88   
1         Matematika          90              86                85   
2     Sastra Inggris          82              87                92   
3         Matematika          93              82                85   
4     Sastra Inggris          86              85                88   
5         Matematika          91              83                84   
6   Sastra Indonesia          88              80                90   
7   Sastra Indonesia          84              82                88   
8     Sastra Inggris          79              89                85   
9     Sastra Inggris          83              88                81   
10    Sastra Inggris          82              85                84   

    Prestasi Siswa  Prestasi Sekolah  
0                1                 1  
1                1                 2  
2                2                 1  
3                1                 1  
4                1                 1  
5                2                 2  
6                2                 1  
7                1                 1  
8                1                 1  
9                2                 2  
10               2                 1

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Jurusan           11 non-null     object
 1   Matematika        11 non-null     int64 
 2   Bahasa Inggris    11 non-null     int64 
 3   Bahasa Indonesia  11 non-null     int64 
 4   Prestasi Siswa    11 non-null     int64 
 5   Prestasi Sekolah  11 non-null     int64 
dtypes: int64(5), object(1)
memory usage: 656.0+ bytes


In [ ]:
X_train = df_train.drop(["Jurusan"], axis=1).values
y_train = df_train["Jurusan"].values

X_test = df_test.drop(["Jurusan"], axis=1).values
y_test = df_test["Jurusan"].values

In [ ]:
X_train

array([[92, 86, 88,  1,  1],
       [90, 86, 85,  1,  2],
       [82, 87, 92,  2,  1],
       [93, 82, 85,  1,  1],
       [86, 85, 88,  1,  1],
       [91, 83, 84,  2,  2],
       [88, 80, 90,  2,  1],
       [84, 82, 88,  1,  1],
       [79, 89, 85,  1,  1],
       [83, 88, 81,  2,  2],
       [82, 85, 84,  2,  1]])

In [ ]:
classifier_model_multiclass = GaussianNB()
classifier_model_multiclass.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_predict = classifier_model_multiclass.predict(X_test)
print("Prediksi Naive Bayes : ",y_predict)

Prediksi Naive Bayes :  ['Matematika' 'Matematika' 'Sastra Indonesia' 'Sastra Indonesia'
 'Sastra Inggris' 'Sastra Indonesia']


In [ ]:
classifier_model_multiclass.predict_proba(X_test)

array([[9.84514205e-01, 1.54850655e-02, 7.29022414e-07],
       [9.99987686e-01, 0.00000000e+00, 1.23143756e-05],
       [2.29659067e-20, 9.99999810e-01, 1.90218794e-07],
       [2.13516750e-09, 9.99999996e-01, 1.89843957e-09],
       [2.44441357e-13, 6.49045316e-06, 9.99993510e-01],
       [1.39716921e-06, 9.99998424e-01, 1.78428054e-07]])

In [ ]:
print(classification_report(y_test,y_predict,zero_division=0))

                  precision    recall  f1-score   support

      Matematika       1.00      1.00      1.00         2
Sastra Indonesia       0.67      1.00      0.80         2
  Sastra Inggris       1.00      0.50      0.67         2

        accuracy                           0.83         6
       macro avg       0.89      0.83      0.82         6
    weighted avg       0.89      0.83      0.82         6



In [ ]:
def predict_one(mat,ingg,indo,presis,presek):
  print('Predicted Jurusan : ',classifier_model_multiclass.predict([[mat,ingg,indo,presis,presek]]))
  print('Probabiilty : ',classifier_model_multiclass.predict_proba([[mat,ingg,indo,presis,presek]]))


In [ ]:
predict_one(92,82,85,1,1)

Predicted Jurusan :  ['Matematika']
Probabiilty :  [[9.84514205e-01 1.54850655e-02 7.29022414e-07]]
